### ISSUE TITLE
Write a post about "a dev's guide to user testing"

### ISSUE THREAD

**Issue by smithkelseyj** [eriolhugotest/devs-guide-to#13]
https://eriolhugotest.github.io/devs-guide-to/posts/devs-guide-to-usertesting-resource-2/

**Comment by smithkelseyj** [comment]
hi @Erioldoesdesign is this complete? https://eriolhugotest.github.io/devs-guide-to/posts/devs-guide-to-usertesting-resource-2/

**Comment by Erioldoesdesign** [comment]
I think it is! @smithkelseyj
