### ISSUE TITLE
Go through each live page to check spelling, grammar, errors, and that we’re happy with ‘styling’

### ISSUE THREAD

**Issue by smithkelseyj** [eriolhugotest/devs-guide-to#16]

**Comment by smithkelseyj** [comment]
I'm satisfied with the styling for now. I checked for errors and did PRs. I didn't do a thorough check of spelling and grammar because I did that multiple times when the content was in Google Docs. Let me know if you feel I should do a thorough read-through.

**Comment by Erioldoesdesign** [comment]
Spelling and grammar we can leave to bug reports by users at this point - I'm also confident that if there are any, they are minor :)

**Comment by smithkelseyj** [comment]
Awesome, we're on the same page.
