### ISSUE TITLE
Numbering is messed up in one spot

### ISSUE THREAD

**Issue by smithkelseyj** [eriolhugotest/devs-guide-to#25]
https://eriolhugotest.github.io/devs-guide-to/conducting-a-user-test/#the-structure-

<img width="127" alt="Screen Shot 2022-02-10 at 16 35 05" src="https://user-images.githubusercontent.com/56199177/153443361-0ea90ddd-ee64-433b-8cc0-85bdfb38a530.png">

Number 12 should be number 4. In the code it seems ok. I don't know how to fix this.

<img width="105" alt="Screen Shot 2022-02-10 at 16 35 08" src="https://user-images.githubusercontent.com/56199177/153443573-a896663a-866d-4bbd-8adc-7a4a4a211084.png">

**Comment by Erioldoesdesign** [comment]
I figured out how to fix this as it was happening on the synthesis page - it's the machine getting confused between 'li' and 'ol' and 'ul' markdown/html.

take a look here and see if you think this compromise from my local environment is ok: 
<img width="815" alt="Screenshot 2022-02-14 at 12 37 28" src="https://user-images.githubusercontent.com/11681324/153865613-77882b25-4992-4ae3-a79b-3aadf7b04ec4.png">

@smithkelseyj

**Comment by Erioldoesdesign** [comment]
Added context it's because in the code we had:

1. text
    - tips text
    - across multiple
    - lines
 2. next point
 3. next point
    - sub 
    - points

So the machine thinks that the sub lines are also numbered but is asked not to display numbers so doesn't and displays '-' and then starts counting again from 5 because there are 3 -'s after the number 1.


code 🤦

**Comment by smithkelseyj** [comment]
I like the first option!

**Comment by smithkelseyj** [comment]
looks good now!
